// The 64 hexagrams of the I Ching (King Wen sequence).
// Each row: [number, char, pinyin, name, lower, upper, judgment(Legge), image(Legge), gloss(modern)]
//
// Trigrams are given bottom-to-top as 3-bit arrays (1 = yang/solid, 0 = yin/broken).
// A hexagram's 6-line binary key (bottom line first) = lower trigram + upper trigram.

const TRIGRAMS = {
  qian: { name: "Heaven",   char: "☰", lines: [1, 1, 1] },
  dui:  { name: "Lake",     char: "☱", lines: [1, 1, 0] },
  li:   { name: "Fire",     char: "☲", lines: [1, 0, 1] },
  zhen: { name: "Thunder",  char: "☳", lines: [1, 0, 0] },
  xun:  { name: "Wind",     char: "☴", lines: [0, 1, 1] },
  kan:  { name: "Water",    char: "☵", lines: [0, 1, 0] },
  gen:  { name: "Mountain", char: "☶", lines: [0, 0, 1] },
  kun:  { name: "Earth",    char: "☷", lines: [0, 0, 0] },
};

const RAW = [
  [1,"乾","Qián","The Creative","qian","qian",
   "The Creative works sublime success, furthering through perseverance.",
   "The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.",
   "Pure creative force and initiative. A time to lead, originate, and act with sustained strength — but only persistence keeps the power true."],
  [2,"坤","Kūn","The Receptive","kun","kun",
   "The Receptive brings sublime success, furthering through the perseverance of a mare. The superior man finds friends in the southwest and forgoes friends in the northeast.",
   "The earth's condition is receptive devotion. Thus the superior man who has breadth of character carries the outer world.",
   "Yielding, nurturing receptivity. Strength here is in following, supporting, and giving form to what another initiates. Devotion, not assertion, succeeds."],
  [3,"屯","Zhūn","Difficulty at the Beginning","zhen","kan",
   "Difficulty at the Beginning works supreme success, furthering through perseverance. Nothing should be undertaken; it furthers one to appoint helpers.",
   "Clouds and thunder. Thus the superior man brings order out of confusion.",
   "The hard, chaotic start of something new. Growth is blocked and tangled; don't force forward — gather support and bring order patiently."],
  [4,"蒙","Méng","Youthful Folly","kan","gen",
   "Youthful Folly has success. It is not I who seek the young fool; the young fool seeks me. At the first oracle I inform him; if he asks two or three times, it is importunity.",
   "A spring wells up at the foot of the mountain. Thus the superior man fosters his character by thoroughness in all that he does.",
   "Inexperience and the need to learn. Stay receptive and ask sincerely once; pestering for answers wastes the teaching. Foster character through thoroughness."],
  [5,"需","Xū","Waiting","qian","kan",
   "Waiting. If you are sincere, you have light and success. Perseverance brings good fortune. It furthers one to cross the great water.",
   "Clouds rise up to heaven. Thus the superior man eats and drinks, is joyous and of good cheer.",
   "Patient, confident waiting in the face of danger ahead. Nourish yourself and stay sincere; the right moment will come — forcing it will not."],
  [6,"訟","Sòng","Conflict","kan","qian",
   "Conflict. You are sincere and are being obstructed. A cautious halt halfway brings good fortune. Going through to the end brings misfortune. It furthers one to see the great man, and does not further one to cross the great water.",
   "Heaven and water go their opposite ways. Thus in all his transactions the superior man carefully considers the beginning.",
   "Open conflict and dispute. Even with a just cause, pressing the fight to the bitter end brings ruin. Seek a fair mediator and compromise; consider causes at the outset."],
  [7,"師","Shī","The Army","kan","kun",
   "The Army needs perseverance and a strong man. Good fortune without blame.",
   "In the middle of the earth is water. Thus the superior man increases his masses by generosity toward the people.",
   "Discipline, organization, and collective force under one able leader. Success requires order, a worthy cause, and a commander the people trust."],
  [8,"比","Bǐ","Holding Together","kun","kan",
   "Holding Together brings good fortune. Inquire of the oracle once again whether you possess sublimity, constancy, and perseverance; then there is no blame. Those who are uncertain gradually join. Whoever comes too late meets with misfortune.",
   "On the earth is water. Thus the kings of antiquity bestowed the different states as fiefs and cultivated friendly relations with the feudal lords.",
   "Union and mutual support around a worthy center. Join wholeheartedly and in good time; lasting bonds need a trustworthy core and genuine commitment."],
  [9,"小畜","Xiǎo Xù","Taming Power of the Small","qian","xun",
   "The Taming Power of the Small has success. Dense clouds, no rain from our western region.",
   "The wind drives across heaven. Thus the superior man refines the outward aspect of his nature.",
   "Small forces restrain great ones — gentle, gradual influence rather than power. The time is not ripe for the big move; refine details and bide your time."],
  [10,"履","Lǚ","Treading","dui","qian",
   "Treading upon the tail of the tiger. It does not bite the man. Success.",
   "Heaven above, the lake below. Thus the superior man discriminates between high and low, and thereby fortifies the thinking of the people.",
   "Proceeding carefully in a dangerous situation. With correct, courteous conduct you can step right behind the tiger and not be bitten. Conduct is everything."],
  [11,"泰","Tài","Peace","qian","kun",
   "Peace. The small departs, the great approaches. Good fortune. Success.",
   "Heaven and earth unite. Thus the ruler divides and completes the course of heaven and earth, and so aids the people.",
   "Harmony and flourishing — heaven and earth in communion. A golden, productive time. Maintain it by tending the balance, for prosperity is not permanent."],
  [12,"否","Pǐ","Standstill","kun","qian",
   "Standstill. Evil people do not further the perseverance of the superior man. The great departs; the small approaches.",
   "Heaven and earth do not unite. Thus the superior man falls back upon his inner worth in order to escape the difficulties.",
   "Stagnation and decline — communication breaks down and the petty gain influence. Withdraw, keep your integrity inward, and wait the dark time out."],
  [13,"同人","Tóng Rén","Fellowship with Men","li","qian",
   "Fellowship with Men in the open. Success. It furthers one to cross the great water. The perseverance of the superior man furthers.",
   "Heaven together with fire. Thus the superior man organizes the clans and makes distinctions between things.",
   "Open community and shared purpose. Bonds founded in the open, on universal principles rather than cliques, can accomplish great things together."],
  [14,"大有","Dà Yǒu","Possession in Great Measure","qian","li",
   "Possession in Great Measure. Supreme success.",
   "Fire in heaven above. Thus the superior man curbs evil and furthers good, and thereby obeys the benevolent will of heaven.",
   "Great abundance and influence, clearly possessed. With strength joined to clarity, much is in your hands — hold it modestly and use it for good."],
  [15,"謙","Qiān","Modesty","gen","kun",
   "Modesty creates success. The superior man carries things through.",
   "Within the earth, a mountain. Thus the superior man reduces that which is too much and augments that which is too little; he weighs things and makes them equal.",
   "Genuine modesty that brings lasting success. Greatness kept low and unassuming wins trust and carries things through where pride would fail."],
  [16,"豫","Yù","Enthusiasm","kun","zhen",
   "Enthusiasm. It furthers one to install helpers and to set armies marching.",
   "Thunder comes resounding out of the earth. Thus the ancient kings made music in order to honor merit, and offered it to the Supreme Deity.",
   "Inspired, contagious enthusiasm that moves people to act. Aligned with the natural moment it rallies others — but must rest on real merit, not mere excitement."],
  [17,"隨","Suí","Following","zhen","dui",
   "Following has supreme success. Perseverance furthers. No blame.",
   "Thunder in the middle of the lake. Thus the superior man at nightfall goes indoors for rest and recuperation.",
   "Adapting and following — leading by responsiveness. To be followed, first know how to serve and adapt to others and to the time; rest when rest is due."],
  [18,"蠱","Gǔ","Work on What Has Been Spoiled","xun","gen",
   "Work on What Has Been Spoiled has supreme success. It furthers one to cross the great water. Before the starting point, three days. After the starting point, three days.",
   "The wind blows low on the mountain. Thus the superior man stirs up the people and strengthens their spirit.",
   "Repairing decay and corruption inherited from the past. Confront the rot courageously, understand how it grew, and rebuild — neglect only deepens the damage."],
  [19,"臨","Lín","Approach","dui","kun",
   "Approach has supreme success. Perseverance furthers. When the eighth month comes, there will be misfortune.",
   "The earth above the lake. Thus the superior man is inexhaustible in his will to teach, and without limits in his tolerance and protection of the people.",
   "A favorable, growing approach — influence expanding toward others. Make the most of the rising time, for it will turn; act with care while it lasts."],
  [20,"觀","Guān","Contemplation","kun","xun",
   "Contemplation. The ablution has been made, but not yet the offering. Full of trust they look up to him.",
   "The wind blows over the earth. Thus the kings of old visited the regions of the world, contemplated the people, and gave them instruction.",
   "Contemplation — viewing and being viewed. Step back to see the whole pattern; influence others by example and inner sincerity rather than force."],
  [21,"噬嗑","Shì Hé","Biting Through","zhen","li",
   "Biting Through has success. It is favorable to let justice be administered.",
   "Thunder and lightning. Thus the kings of former times made firm the laws through clearly defined penalties.",
   "An obstacle must be bitten through decisively. Where something blocks union, energetic, clear-cut action — even penalty — removes it. Hesitation prolongs the problem."],
  [22,"賁","Bì","Grace","li","gen",
   "Grace has success. In small matters it is favorable to undertake something.",
   "Fire at the foot of the mountain. Thus does the superior man proceed when clearing up current affairs, but he dares not decide controversial issues in this way.",
   "Beauty, form, and grace. Adornment and good form bring success in lesser things, but substance must underlie the surface — style alone settles nothing major."],
  [23,"剝","Bō","Splitting Apart","kun","gen",
   "Splitting Apart. It does not further one to go anywhere.",
   "The mountain rests on the earth. Thus those above can ensure their position only by giving generously to those below.",
   "Disintegration — dark forces undermining from below. Don't act or resist directly; wait, secure your foundations, and let the decay run its course."],
  [24,"復","Fù","Return","zhen","kun",
   "Return. Success. Going out and coming in without error. Friends come without blame. To and fro goes the way. On the seventh day comes return.",
   "Thunder within the earth. Thus the kings of antiquity closed the passes at the time of solstice. Merchants and strangers did not go about.",
   "The turning point — light returns after the dark. A small new beginning, natural and not forced. Rest, let the tender new energy gather strength before acting."],
  [25,"無妄","Wú Wàng","Innocence","zhen","qian",
   "Innocence. Supreme success. Perseverance furthers. If someone is not as he should be, he has misfortune, and it does not further him to undertake anything.",
   "Under heaven thunder rolls. Thus the kings of old, rich in virtue, nourished all beings.",
   "Innocent spontaneity, acting from one's true nature without calculation. Stay aligned with what is right and unforced; scheming or deviation invites trouble."],
  [26,"大畜","Dà Xù","Taming Power of the Great","qian","gen",
   "The Taming Power of the Great. Perseverance furthers. Not eating at home brings good fortune. It furthers one to cross the great water.",
   "Heaven within the mountain. Thus the superior man acquaints himself with many sayings of antiquity and many deeds of the past, in order to strengthen his character.",
   "Great restraint that stores up strength. Holding firm energy in check builds power and character. Accumulate wisdom now; great undertakings become possible."],
  [27,"頤","Yí","Corners of the Mouth","zhen","gen",
   "The Corners of the Mouth. Perseverance brings good fortune. Pay heed to the providing of nourishment and to what a man seeks to fill his own mouth with.",
   "At the foot of the mountain, thunder. Thus the superior man is careful of his words and temperate in eating and drinking.",
   "Nourishment — what you take in and what you give out. Be mindful of how you feed body, mind, and others; words and intake shape character."],
  [28,"大過","Dà Guò","Preponderance of the Great","xun","dui",
   "Preponderance of the Great. The ridgepole sags to the breaking point. It furthers one to have somewhere to go. Success.",
   "The lake rises above the trees. Thus the superior man, when he stands alone, is unconcerned, and if he has to renounce the world, he is undaunted.",
   "Critical overload — the structure is overstrained and near collapse. Extraordinary times need extraordinary, decisive measures; act to relieve the pressure before it breaks."],
  [29,"坎","Kǎn","The Abysmal Water","kan","kan",
   "The Abysmal repeated. If you are sincere, you have success in your heart, and whatever you do succeeds.",
   "Water flows on uninterruptedly and reaches its goal. Thus the superior man walks in lasting virtue and carries on the business of teaching.",
   "Repeated danger, like water in a chasm. Don't panic or thrash; stay sincere and true to yourself, flow on steadily, and the danger can be navigated."],
  [30,"離","Lí","The Clinging Fire","li","li",
   "The Clinging. Perseverance furthers. It brings success. Care of the cow brings good fortune.",
   "That which is bright rises twice. Thus the great man, by perpetuating this brightness, illumines the four quarters of the world.",
   "Clarity, attachment, and dependence — like fire clinging to its fuel. Brightness illuminates, but it must cling to something solid. Cultivate clarity and devotion."],
  [31,"咸","Xián","Influence","gen","dui",
   "Influence. Success. Perseverance furthers. To take a maiden to wife brings good fortune.",
   "A lake on the mountain. Thus the superior man encourages people to approach him by his readiness to receive them.",
   "Mutual attraction and influence — the courtship of opposites. Genuine response comes from an open, receptive heart, not manipulation. Stay open and sincere."],
  [32,"恆","Héng","Duration","xun","zhen",
   "Duration. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.",
   "Thunder and wind: the image of Duration. Thus the superior man stands firm and does not change his direction.",
   "Endurance and constancy — lasting through steady renewal. Hold a firm course and consistent principles; duration comes from enduring movement, not standing still."],
  [33,"遯","Dùn","Retreat","gen","qian",
   "Retreat. Success. In what is small, perseverance furthers.",
   "Mountain under heaven. Thus the superior man keeps the inferior man at a distance, not angrily but with reserve.",
   "Strategic withdrawal in the face of advancing negativity. Retreat is not defeat — timed well, it preserves strength and dignity. Yield ground, keep your reserve."],
  [34,"大壯","Dà Zhuàng","Power of the Great","qian","zhen",
   "The Power of the Great. Perseverance furthers.",
   "Thunder in heaven above. Thus the superior man does not tread upon paths that do not accord with established order.",
   "Great power and vigor at its height. Strength is real now, but true power keeps within right limits; brute force without restraint or correctness turns destructive."],
  [35,"晉","Jìn","Progress","kun","li",
   "Progress. The powerful prince is honored with horses in large numbers. In a single day he is granted audience three times.",
   "The sun rises over the earth. Thus the superior man himself brightens his bright virtue.",
   "Rapid, easy advancement — the sun rising over the earth. Recognition and progress come readily; rise with clarity and brighten your own virtue as you go."],
  [36,"明夷","Míng Yí","Darkening of the Light","li","kun",
   "Darkening of the Light. In adversity it furthers one to be persevering.",
   "The light has sunk into the earth. Thus the superior man lives with the great mass: he veils his light, yet still shines.",
   "A time when the light is hidden and the dark prevails. Protect your inner light by veiling it; endure adversity quietly, keep your principles concealed but intact."],
  [37,"家人","Jiā Rén","The Family","li","xun",
   "The Family. The perseverance of the woman furthers.",
   "Wind comes forth from fire. Thus the superior man has substance in his words and duration in his way of life.",
   "The clan, household, and right relationships within it. Order in the wider world begins at home; each member holding their proper role brings harmony outward."],
  [38,"睽","Kuí","Opposition","dui","li",
   "Opposition. In small matters, good fortune.",
   "Above, fire; below, the lake. Thus amid all fellowship the superior man retains his individuality.",
   "Estrangement and opposition — fire and water pulling apart. Reconciliation is possible only in small steps. Hold to common ground while keeping your own stance."],
  [39,"蹇","Jiǎn","Obstruction","gen","kan",
   "Obstruction. The southwest furthers. The northeast does not further. It furthers one to see the great man. Perseverance brings good fortune.",
   "Water on the mountain. Thus the superior man turns his attention to himself and molds his character.",
   "A serious obstacle blocks the path. Don't batter against it head-on; pause, turn inward, seek allies and counsel, and find the way around rather than through."],
  [40,"解","Xiè","Deliverance","kan","zhen",
   "Deliverance. The southwest furthers. If there is no longer anything where one has to go, return brings good fortune. If there is still something where one has to go, hasten there.",
   "Thunder and rain set in. Thus the superior man pardons mistakes and forgives misdeeds.",
   "Release after tension — the storm breaks and difficulty resolves. Return to normal life, forgive, clear away the leftover trouble promptly, and don't dwell on the past."],
  [41,"損","Sǔn","Decrease","dui","gen",
   "Decrease combined with sincerity brings about supreme good fortune without blame. One may be persevering in this. It furthers one to undertake something. How is this to be carried out? One may use two small bowls for the sacrifice.",
   "At the foot of the mountain, the lake. Thus the superior man controls his anger and restrains his instincts.",
   "Decrease — deliberate simplifying, giving up the lower for the higher. Sincere sacrifice of excess strengthens what matters. Less, offered truly, is enough."],
  [42,"益","Yì","Increase","zhen","xun",
   "Increase. It furthers one to undertake something. It furthers one to cross the great water.",
   "Wind and thunder: the image of Increase. Thus the superior man: if he sees good, he imitates it; if he has faults, he rids himself of them.",
   "Increase — a generous, expansive time when those above give to those below. Bold undertakings are favored. Grow by emulating good and shedding faults."],
  [43,"夬","Guài","Breakthrough","qian","dui",
   "Breakthrough. One must resolutely make the matter known at the court of the king. It must be announced truthfully. Danger. It is necessary to notify one's own city. It does not further to resort to arms. It furthers one to undertake something.",
   "The lake has risen up to heaven. Thus the superior man dispenses riches downward and refrains from resting on his virtue.",
   "A decisive breakthrough — the last of the dark must be resolutely cleared away. Act openly and truthfully, not by force; root out the wrong without becoming it."],
  [44,"姤","Gòu","Coming to Meet","xun","qian",
   "Coming to Meet. The maiden is powerful. One should not marry such a maiden.",
   "Under heaven, wind. Thus the prince acts when he disseminates his commands and proclaims them to the four quarters of heaven.",
   "An unexpected encounter — something seemingly small and inviting that conceals power. Be alert: a single dark element returning can spread if welcomed unguardedly."],
  [45,"萃","Cuì","Gathering Together","kun","dui",
   "Gathering Together. Success. The king approaches his temple. It furthers one to see the great man. This brings success. Perseverance furthers. To bring great offerings creates good fortune.",
   "The lake rises up above the earth. Thus the superior man renews his weapons in order to meet the unforeseen.",
   "Gathering and concentration — people drawn together around a center. Union needs a worthy leader and shared purpose; stay prepared for the frictions crowds bring."],
  [46,"升","Shēng","Pushing Upward","xun","kun",
   "Pushing Upward has supreme success. One must see the great man. Fear not. Departure toward the south brings good fortune.",
   "Within the earth, wood grows. Thus the superior man of devoted character heaps up small things in order to achieve something high and great.",
   "Effortful, gradual ascent — like a plant pushing up through soil. Steady, devoted growth step by step leads upward. Don't rest; keep rising while the way is open."],
  [47,"困","Kùn","Oppression","kan","dui",
   "Oppression. Success. Perseverance. The great man brings about good fortune. No blame. When one has something to say, it is not believed.",
   "There is no water in the lake. Thus the superior man stakes his life on following his will.",
   "Exhaustion and adversity — hemmed in and drained, words falling on deaf ears. Stay inwardly cheerful and true; a test of character to be endured, not argued away."],
  [48,"井","Jǐng","The Well","xun","kan",
   "The Well. The town may be changed, but the well cannot be changed. It neither decreases nor increases. They come and go and draw from the well. If one gets down almost to the water and the rope does not go all the way, or the jug breaks, it brings misfortune.",
   "Water over wood. Thus the superior man encourages the people at their work, and exhorts them to help one another.",
   "The well — the deep, unchanging source that nourishes all. What is essential and communal endures beneath surface change. Draw fully and don't let the effort fail at the last."],
  [49,"革","Gé","Revolution","li","dui",
   "Revolution. On your own day you are believed. Supreme success, furthering through perseverance. Remorse disappears.",
   "Fire in the lake. Thus the superior man sets the calendar in order and makes the seasons clear.",
   "Radical change and revolution — the old order must be overturned. Time it rightly and people will trust it; change made at the right moment renews everything."],
  [50,"鼎","Dǐng","The Cauldron","xun","li",
   "The Cauldron. Supreme good fortune. Success.",
   "Fire over wood. Thus the superior man consolidates his fate by making his position correct.",
   "The sacred cauldron — transformation, nourishment, and culture. A vessel that cooks raw into refined. Support what is worthy; a time of establishing and elevating."],
  [51,"震","Zhèn","The Arousing Thunder","zhen","zhen",
   "Shock brings success. Shock comes — oh, oh! Laughing words — ha, ha! The shock terrifies for a hundred miles, and he does not let fall the sacrificial spoon and chalice.",
   "Thunder repeated: the image of Shock. Thus in fear and trembling the superior man sets his life in order and examines himself.",
   "Sudden shock and upheaval — thunder that startles everyone. The one who stays composed through the jolt comes through unharmed. Let shock prompt self-examination, not panic."],
  [52,"艮","Gèn","Keeping Still, Mountain","gen","gen",
   "Keeping Still. Keeping his back still so that he no longer feels his body. He goes into his courtyard and does not see his people. No blame.",
   "Mountains standing close together: the image of Keeping Still. Thus the superior man does not permit his thoughts to go beyond his situation.",
   "Stillness and meditation — knowing when to stop. Quiet the restless mind; act only when the time is right and rest when it is not. Inner calm brings clarity."],
  [53,"漸","Jiàn","Development","gen","xun",
   "Development. The maiden is given in marriage. Good fortune. Perseverance furthers.",
   "On the mountain, a tree: the image of Development. Thus the superior man abides in dignity and virtue, in order to improve the mores.",
   "Gradual, well-rooted progress — development advancing step by step like a tree growing. Nothing skipped, each stage earned. Patience and right order bring lasting growth."],
  [54,"歸妹","Guī Mèi","The Marrying Maiden","dui","zhen",
   "The Marrying Maiden. Undertakings bring misfortune. Nothing that would further.",
   "Thunder over the lake: the image of the Marrying Maiden. Thus the superior man understands the transitory in the light of the eternity of the end.",
   "Entering a relationship from a subordinate or irregular position. Acting impulsively here misfires. Understand the limits of the situation and tread with great tact and restraint."],
  [55,"豐","Fēng","Abundance","li","zhen",
   "Abundance has success. The king attains abundance. Be not sad. Be like the sun at midday.",
   "Both thunder and lightning come: the image of Abundance. Thus the superior man decides lawsuits and carries out punishments.",
   "Peak abundance and fullness — the sun at its zenith. Use the height of plenty knowing it cannot last; clarity and decisive action keep the fullness from tipping to decline."],
  [56,"旅","Lǚ","The Wanderer","gen","li",
   "The Wanderer. Success through smallness. Perseverance brings good fortune to the wanderer.",
   "Fire on the mountain: the image of the Wanderer. Thus the superior man is clear-minded and cautious in imposing penalties, and protracts no lawsuits.",
   "The traveler far from home, without firm ground. Stay modest, reserved, and correct; a stranger survives by good conduct and not overstepping. Keep to small, careful aims."],
  [57,"巽","Xùn","The Gentle Wind","xun","xun",
   "The Gentle. Success through what is small. It furthers one to have somewhere to go. It furthers one to see the great man.",
   "Winds following one upon another: the image of the Gently Penetrating. Thus the superior man spreads his commands abroad and carries out his undertakings.",
   "Gentle, persistent influence — like wind that penetrates everywhere over time. Mild, steady, repeated effort accomplishes what force cannot. Clear aims plus patience win through."],
  [58,"兌","Duì","The Joyous Lake","dui","dui",
   "The Joyous. Success. Perseverance is favorable.",
   "Lakes resting one on the other: the image of the Joyous. Thus the superior man joins with his friends for discussion and practice.",
   "Joy, openness, and pleasure shared. True, inner gladness is contagious and encouraging. Joy grounded in sincerity strengthens; cultivate it through honest exchange with others."],
  [59,"渙","Huàn","Dispersion","kan","xun",
   "Dispersion. Success. The king approaches his temple. It furthers one to cross the great water. Perseverance furthers.",
   "The wind drives over the water: the image of Dispersion. Thus the kings of old sacrificed to the Lord and built temples.",
   "Dissolution — dispersing rigidity, ego, and hardness that block flow. Melt the barriers and divisions; a unifying idea or devotion can gather the scattered back together."],
  [60,"節","Jié","Limitation","dui","kan",
   "Limitation. Success. Galling limitation must not be persevered in.",
   "Water over lake: the image of Limitation. Thus the superior man creates number and measure, and examines the nature of virtue and correct conduct.",
   "Setting limits and boundaries — a lake holds only so much. Sensible self-restraint brings freedom and success; but limits taken to bitter extremes defeat their own purpose."],
  [61,"中孚","Zhōng Fú","Inner Truth","dui","xun",
   "Inner Truth. Pigs and fishes. Good fortune. It furthers one to cross the great water. Perseverance furthers.",
   "Wind over lake: the image of Inner Truth. Thus the superior man discusses criminal cases in order to delay executions.",
   "Inner sincerity and trust that reaches even the dullest hearts. Genuine truthfulness at the core moves others without coercion; act from a sincere center and influence follows."],
  [62,"小過","Xiǎo Guò","Preponderance of the Small","gen","zhen",
   "Preponderance of the Small. Success. Perseverance furthers. Small things may be done; great things should not be done. The flying bird brings the message: it is not well to strive upward, it is well to remain below. Great good fortune.",
   "Thunder on the mountain: the image of Preponderance of the Small. Thus the superior man in his conduct gives preponderance to reverence.",
   "A time for small, careful steps, not grand ambitions. Exceed slightly in modesty and conscientiousness, not in reach. Stay low like the bird that should not fly too high."],
  [63,"既濟","Jì Jì","After Completion","li","kan",
   "After Completion. Success in small matters. Perseverance furthers. At the beginning, good fortune; at the end, disorder.",
   "Water over fire: the image of the condition After Completion. Thus the superior man takes thought of misfortune and arms himself against it in advance.",
   "Everything is in order — completion achieved, but the peak is precarious. The danger now is complacency. Guard the order vigilantly, for at the height things begin to slip."],
  [64,"未濟","Wèi Jì","Before Completion","kan","li",
   "Before Completion. Success. But if the little fox, after nearly completing the crossing, gets his tail in the water, there is nothing that would further.",
   "Fire over water: the image of the condition Before Completion. Thus the superior man is careful in the differentiation of things, so that each finds its place.",
   "On the threshold of completion — the goal in sight but not yet reached. Success is near and possible; this final stretch demands the most care. Don't get careless at the last step."],
];

const HEXAGRAMS = RAW.map(([number, char, pinyin, name, lower, upper, judgment, image, gloss]) => {
  const lines = [...TRIGRAMS[lower].lines, ...TRIGRAMS[upper].lines]; // bottom -> top
  return { number, char, pinyin, name, lower, upper, judgment, image, gloss, lines, key: lines.join("") };
});

// Lookup: 6-bit binary key (bottom line first) -> hexagram object.
const BY_KEY = Object.fromEntries(HEXAGRAMS.map((h) => [h.key, h]));

function hexagramFromLines(lines /* array of 6 values, bottom->top, 1=yang 0=yin */) {
  return BY_KEY[lines.join("")];
}
